version: "{build}"
clone_folder: "c:\\dns"

environment:
  global:
    CABOPTS:  "--store-dir=C:\\SR --http-transport=plain-http"
  matrix:
    - GHCVER: "8.6.5"

platform:
#  - x86 # We may want to test x86 as well, but it would double the 23min build time.
  - x64

cache:
 - "C:\\SR"

install:
 - "choco install -y cabal"
 - "choco install -y ghc --version %GHCVER%"
 - "refreshenv"
 - "set PATH=C:\\msys64\\mingw64\\bin;C:\\msys64\\usr\\bin;C:\\ghc\\ghc-%GHCVER%\\bin;%PATH%"
 - "cabal --version"
 - "ghc --version"
 - "cabal %CABOPTS% new-update"
 - "cabal %CABOPTS% new-install hspec-discover"

build: off
deploy: off

test_script:
 - cabal %CABOPTS% new-build -j1 -vnormal+nowrap --dry all
 - ps: Push-AppveyorArtifact dist-newstyle\cache\plan.json
 - cabal %CABOPTS% new-build -j1 -vnormal+nowrap all
 - cabal %CABOPTS% new-test  -j1 -vnormal+nowrap all
 - ps: ls dns*.log -recurse | %{ Push-AppveyorArtifact $_}
