name: ci
on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        ghc: ['8.0', '8.2', '8.4', '8.6', '8.8', '8.10']
        exclude:
        - os: windows-latest
          ghc: "8.0"
        - os: windows-latest
          ghc: "8.2"
        - os: windows-latest
          ghc: "8.4"
        - os: windows-latest
          ghc: "8.6"
        - os: windows-latest
          ghc: "8.8"
    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: '3.2'
    - name: Update cabal package database
      run: |
        cabal update
        cabal freeze
    - uses: actions/cache@v2
      name: Cache cabal stuff
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-
    - name: Build
      run: |
        cabal build --disable-tests --disable-benchmarks all
    - name: Test
      run: |
        cabal test
    - name: Haddock
      run: |
        cabal haddock
    - name: SDist
      run: |
        cabal sdist all
